### ISSUE TITLE
Why does tpl not support float type ? 

### ISSUE THREAD

**Issue by blackball** [troydhanson/tpl#11]
I have been used tpl in some projects before, and recently, I need(have) to dump 'float' type data. I checked the source codes of tpl, and found it was not hard to add 'float' support. Why was it not supported in the beginning ? Or I missed some reason ? Thanks very much!

**Comment by troydhanson** [comment]
Hi, I omitted it originally because float and its big brother, double, are apparently less portable. In other words the endian handling and format varies more than the integer types from platform to platform. I guess the best compromise it to add two types (a 4 byte float and a 8 byte double) with the caveats that they might only work when packed and unpacked on the same architecture. Feel free to send a pull request if you want to try it out.

**Comment by blackball** [comment]
Hi, thanks for your reply. 

I considered the way you mentioned above, using 4 byte to pack a float, but found it was a burden for me. So I simply added a keyword 'F' for float support in my own fork. Most of my use cases are simple, and will be operated in a Intel x86_64 machine with IEEE754 supported, so, I think the 'portability 'will be OK. Tpl is a clean and useful library, thanks for this work.
