### ISSUE TITLE
Trouble sending data over network.

### ISSUE THREAD

**Issue by note89** [troydhanson/tpl#13]
```
typedef struct DataGram {
    char* data;
    char header;
};

```

```
    struct DataGram temp;
    temp.header = 'm';
    temp.data = "ppp";

    char* buffert;
    size_t i, length;
    tpl_node *tn;
    struct DataGram s1;



   printf( "input map{%s}\n", temp.data);

    tn = tpl_map( "S(sc)", &temp );  /* pass structure address */
    tpl_pack( tn, 0 );
    tpl_dump( tn, TPL_MEM,&buffert, &length  );//&buffert, &length 
    tpl_free( tn );


    printf( "size = %lu\n", length );


     for(;;)
     {
        sendto(sockfd, buffert, length,0,(struct sockaddr *)&cliaddr,sizeof(cliaddr));
     }
```

```
length=recvfrom(sockfd,buffert,10000,0,NULL,NULL);
        printf("i got a message,client got %d bytes \n",length);
        tn = tpl_map( "S(sc)", &s1 );
        tpl_load( tn, TPL_MEM, buffert, length );
        tpl_unpack( tn, 0 );
        tpl_free( tn );
        //free( buffert );

        char header = 'p';
        printf("data %s", s1.data);
```

If we only have one value in our struct then we are able to unpack it at the client side. 
But if we use two values in our struct then we get -1 bytes sent. why?

**Comment by troydhanson** [comment]
Hi, you'll need to use format string S(sc) for that structure.

**Comment by Niler851** [comment]
Knew changing the example inline to a earlier problem was bad. we did have it as S(sc).

**Comment by troydhanson** [comment]
Well there are a few things to do. First, check the return value from sendto. If it's -1 you should print strerror(errno). The errno may be EMSGSIZE. This may happen if you have a long string in data. 

It is is the same with recvfrom. You need to check for -1 return value and print the message. These are two separate program snippets right? The allocation of buffert for the bottom one is not shown. You need to declare it like char buffert[10000] so that recvfrom has some place to copy to.
