### ISSUE TITLE
Fail to load linked list

### ISSUE THREAD

**Issue by s211897-studentipolito** [troydhanson/tpl#14]
Hi Troy,
I have this linked list:
```
typedef struct list_t {
	char* directory;
	char *fsName;
	char* album;
	char* title;
	char* artist;
	struct list_t *next;
	struct list_t *prev;
} list_t;
```

and I succeded in serializing it (I think) but it fails to load every time.
This is the code:
```
void serialize (list_t *listDB)
{
	tpl_node *tn;
	list_t *i, tmp;

	tn = tpl_map ("A(S(sssss))", &tmp);
	for (i = listDB; i != NULL; i = i->next) {
		tmp = *i;
		tpl_pack (tn, 1);
	}
	tpl_dump (tn, TPL_FILE, "list.tpl");
	tpl_free (tn);
}

list_t *deserialize ()
{
	tpl_node *tn;
	list_t *listDB, tmp, *new;
	
	tn = tpl_map ("(A(S(sssss))", &tmp);
	tpl_load (tn, TPL_FILE, "list.tpl");
	/*tpl_unpack ( fin*/
	listDB = malloc (sizeof (list_t));
	*listDB = tmp;

	while (tpl_unpack (tn, 1) > 0) {
		new = malloc (sizeof (list_t));
		*new = tmp;
		listDB = link (listDB, new);
	}

	return listDB;
}
```

It gives me: failed to parse (A(S(sssss))

How can I solve this?

**Comment by troydhanson** [comment]
Hi, you have an extra parenthesis before the A. That causes the parse error. Also, on a separate note, in your deserialize routine, you could eliminate the two lines where you allocate and assign listDB. Instead you can set listDB to NULL on function entry then change your link(...) line to this:

    listDB = listDB ? link(listDB, new) : new;

**Comment by maglamaniac** [comment]
Hello,
I was looking at the macro utarray_new which calls malloc without checking if it succeeded. Is this intentional? If malloc fails wont the next call to utarray_init cause a crash?

`#define utarray_new(a,_icd) `do` {                         \
  a=(UT_array*)malloc(sizeof(UT_array));           \
  utarray_init(a,_icd);                                                 \
} while(0)
`
Thanks

**Comment by troydhanson** [comment]
Thanks @maglamaniac- I made a correction to utarray.h to invoke the oom macro if malloc fails.

**Comment by maglamaniac** [comment]
Thanks. I was trying to commit the same exact change but I am new to github
and was struggling to get my changes pushed up due to permission issues.
If I want to help out and make other changes do I need special permission
from you to push them up to your repo? I was hoping to become a contributor.

Thanks again
Al

**Comment by troydhanson** [comment]
Hi Al, with github you can click "Fork" and get your own copy of the repo, where you make the changes. Once you are happy with them, you can submit a pull request back to me. Then I can click a button to accept and merge your changes into my repo.
