### ISSUE TITLE
Build issue with MinGW in Windows

### ISSUE THREAD

**Issue by matwachich** [troydhanson/tpl#5]
Hi!
I have a problem when compiling the lib with MinGW in Windows (no cygwin):
I build it either as a static lib or a dll (with TPL_EXPORTS defined)
In both ones, I have linker errors:
undefined reference to '_imp__tpl_xxx' (xxx = all tpl functions)

I can't figure where is the problem. Thanks :)

**Comment by amullins83** [comment]
In order to get this to work, you need to install MinGW with all of the autotools commands (which is not the default, but can be added in the MinGW package GUI). Also, there appears to be a problem running make after ./configure (may be specific to my crazy system). It looks like tpl.c checks to see if `_WIN32` is defined before including `<inttypes>`. Then it includes tpl.h, which checks to see if `_MSC_VER` is defined before including `<inttypes>`. Running gcc in MinGW causes both of these to do the wrong thing, so there's a conflict between `typedef __int32 int32_t` in tpl.c and `typedef int int32_t` in `<stdtypes>`. Sorry if that didn't make sense, but if we're including `<inttypes>` in tpl.h anyway, why bother defining them in tpl.c?

**Comment by amullins83** [comment]
Update: removing the `inttypes` stuff from tpl.c did allow tpl.c to compile, but I don't quite understand the linker script. I think this is a case where autotools is failing MinGW, since the script seems to assume that, since this is Windows, MSVC is going to be producing these `_imp__` symbols. The script then calls the GCC linker (since that's my default linker), and then those symbols are undefined. My autotools script foo is not strong, but I'm interested in solving this if I can.

**Comment by troydhanson** [comment]
Hi, it's been several years since I last used MinGW or even Visual Studio for that matter. It "used to" work on MinGW, but like you say, I probably had the autotools stuff installed. I am unable to test MinGW or VS changes. If you have a fix that you're confident makes it work better feel free to send me a pull request.
